### ISSUE TITLE
Missing dependencies

### ISSUE THREAD

**Issue by Alexander-Wilms** [flathub/org.musescore.MuseScore#2]
This [manifest](https://github.com/musescore/MuseScore/pull/3115/files#diff-1999a999917ca1e430c31aa6bda85e24) contains some more dependencies, which could be added to the flathub version.

I opened that pull request before I knew one could just add QtWebKit as a module. Since your manifest builds a stable version, should I close my pull request and you would open a new one?

**Comment by jurf** [comment]
I am not entirely sure about the manifest here (e.g. why it renders fonts worse when use the system freetype and why ARM and 32-bit builds fail), and I wanted to wait until QtWebkit gets into the runtime.

But I dunno, maybe it’s a good idea to do the PR anyway, and update it later.

Regarding the deps, I think I actually built it off your manifest, but some of the deps you have aren’t needed (e.g. `portaudio` and `jack` are useless in Flatpak, and poppler I think isn’t even normally, but it’s quite some time since I’ve done it, I don’t remember exactly), and others are supplied with MuseScore so I just left them.

I don’t really have time to experiment with it ATM, but feel free if you want.

**Comment by Alexander-Wilms** [comment]
I think I'll get to it in March.

**Comment by jurf** [comment]
Eh, where did March go? ;-)

Anyway, just opened a new PR that adds PortMidi, but regarding the other deps, I think MuseScore bundles them and doesn’t even use the system libraries (haven’t checked though), e.g. OGG/PDF export works fine without additional deps. Even [Arch](https://www.archlinux.org/packages/community/x86_64/musescore/) doesn’t use them, and it uses everything it can usually.

I haven’t had a single problem with this yet so I’ll close this, please re-open if you find any issues.
